# Add this location block to your existing nginx config on vpsmikewolf.duckdns.org
# (wherever your server {} block is, e.g. /etc/nginx/sites-available/default)

location /api/scs/ {
    proxy_pass http://127.0.0.1:4242/api/scs/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
    add_header Access-Control-Allow-Headers "Content-Type, x-mod-token";
    if ($request_method = OPTIONS) { return 204; }
}
